---
# Description of the format
# =========================
# See README.md file
#
default: &default
  :namespace: Wizcorp::Couchbase
  :class: BucketStats
  :function: :avg               # :avg, :sum, :none
  :operator: :>                 # Can be :>, :< ,:==, :!=
  :rag: [0,0,0]                 # order Red, Amber, Green

# Checks for values that should be close to or 0 most of the times.
zero_10: &zero_10
  <<: *default
  :rag:  [20, 10, -1]



# ======================
# END of defaults
# ======================

:ep_tap_replica_queue_backfillremaining:
  <<: *zero_10

:ep_tap_total_qlen:
  <<: *zero_10

:vb_active_queue_size:
  <<: *default
  :rag: [100,80,-1]
    
:vb_replica_queue_size:
  <<: *default
  :rag: [100,80,-1]
    
:avg_disk_commit_time:
  <<: *default
  :rag: [50,40,0]

:ep_tap_total_queue_drain:
  <<: *default
  :rag: [100,80,-1]

:ep_tap_total_queue_backoff:
  <<: *default
  :rag: [50,10,-1]

:ep_tap_total_queue_itemondisk:
  <<: *default
  :rag: [50,10,-1]

:ep_tap_replica_queue_itemondisk:
  <<: *default
  :rag: [50,10,-1]
