---
# Description of the format
# =========================
# See README.md file
#
default: &default
  :namespace: Wizcorp::Couchbase
  :class: BucketStats
  :function: :none 
  :operator: :>
  :rag: [0,0,0]  # order Red, Amber, Green


# ======================
# END of defaults
# ======================

:ep_tap_replica_queue_backfillremaining:
  <<: *default
  :function: :sum
  :rag:  [20, 10, -1]

:ep_tap_total_count:
  <<: *default
  :rag: [5,1,0]
  :function: :avg


:avg_disk_commit_time:
  <<: *default
  :rag: [0,0,-1]
  :function: :sum
