
:run_as: nagios
:rvm: ruby-1.9.3-p327
:log: /var/log/nagios3/nagira.log

:nagios:
  :hostgroup: couchbase

  :api:
    :hostname: nagios
    :port: 4567

:buckets:
#   :buckets:
#     - defauls
#   :hostgroups:
#     - membase_slaves
#     - membase_masters
#   :except:
#     - dummy.moria.local
#   :hosts:

#
# This is version beta config. Will be changed later.
#
  cbm1:
    - default
    #    - another
  cbm2:
    - default
    #    - another
