
# UNIX is to run application with
:run_as: nagios

# RVM version
:rvm: ruby-1.9.3-p327

# This log file should be accessible with ID above
:log: /var/log/nagios3/nagira.log


#
# Hosts configuration for the application.
# Hosts list will be rerived from Nagira API on start
#
:nagios:
  :hostgroups: [membase_masters, membase_slaves]
  :erb: erb/couchbase.cfg.erb

  :api:
    :hostname: nagios
    :port: 4567

:buckets:
  - default
